### ISSUE TITLE
JSON DIFF 기능 개발

### ISSUE THREAD

**Issue by Kyoo130** [Kyoo130/pilot-json-diff#2]
## 이슈 내용
- JSON DIFF 기능 개발

## 작업 상세
- [x] JSON 입력창 컴포넌트 개발
- [x] JSON 비교 기능 개발

## 작업 예상 일정
- ~2022.06.01 ~ 2022.06.02~ 
- 2021.06.01~ 2022.06.05
  - vue-code-diff 라이브러리 삭제 후 기능 개발 필요로 인한 작업 일정 변경

## 기타 사항
- #1 완료 후 개발 진행하여 2022.06.02 작업 완료 예상됨
- `요구사항1` 개발 후 피드백 요청 예정

**Comment by Kyoo130** [comment]
## 개발 이슈

### 1. Router 적용 후 상태 관리 이슈 발생
+ 변경 전 기획
  + App.vue에서 data를 관리하도록 설계
  + Home 경로에서 비교 코드 입력 후 제출 버튼 클릭 시 Detail 경로 이동 및 비교 결과 보여주도록 설계
   
+ 이슈 사항
  + `Editor.vue`에서 data 변경 시 `Editor.vue` > `Home.vue` > `App.vue`(부모의 부모)까지 data를 넘겨주고,
  + 변경된 data를 다시 `Detail.vue` 자식에게 넘겨줘야 하는 상태 관리 이슈 발생

+ 변경 내용
  + `Main.vue` 페이지를 만들어 각각에 Editor를 만들어 부모에게 바로 데이터를 넘겨주도록 개발

+ 해결 방안 (예정 사항)
  + 코드 비교 시 페이지 이동(Home > Detail)한 후 결과 보여지도록 개발 예정 
  + Editor를 컴포넌트화 하여 e.target.value를 통해 각각 전후 data 저장하도록 코드 리팩토링 예정

### 2. CodeDiff 라이브러리 사용 유무 확인
+ 코드를 비교할 수 있는 `CodeDiff`를 사용하여 요구사항과 맞는 내용인지 피드백 확인 후 추가 개발 예정
+ 만약, 라이브러리 사용이 불가할 경우 JSON을 비교하는 코드 추가 개발 필요
```javascript
...
jsonDiff() {
      let isDiff = JSON.stringify(this.obj1) === JSON.stringify(this.obj2);
      console.log(isDiff);
    }
...
```

**Comment by jaylee-conbus** [comment]
## 1차 피드백

### 1.Router 적용 후 상태 관리 이슈 발생
* 전역 상태관리 라이브러리 사용
  * Vue에도 redux와 동일한 전역 상태관리 라이브러리가 있습니다. 해당 라이브러리 참고하셔서 적용해보는것도 좋을것 같습니다.
* Props에 단반향 데이터 흐름에 대해 다시 생각해보는것도 좋을수 있습니다.
  * 부모 컴포넌트의 데이터를 자식 컴포넌트에서 바꿀 수 없는것으로 알고 계실텐데 변경 불가능한 범위가 어디까지인지 한번 더 공부하시면 해법이 나올수도 있습니다.  
 * 생각하신것처럼 컴포넌트를 많이 나누는것보다 일단은 메인 페이지하나에 넣는것도 좋은 방법일 수 있습니다. JSON을 비교하는 단일 기능을  가지고 있는 컴포넌트 정도로만 나누어도 될 것 같습니다.
 
 ### 2. CodeDiff 라이브러리 사용 유무 확인
 * 요구사항에선 [JSONDiff](http://www.jsondiff.com/) 처럼 결과가 나오는것을 지향하고 있습니다. 문제 해결을 위해 해당 라이브러리를 추가하신것은 잘하셨으나 직접 JSON을 비교하시는 기능을 구현하시는것이 핵심이므로 직접 JSON을 비교하시는 코드를 만들기 바랍니다.

**Comment by Kyoo130** [comment]
## 개발 이슈

## 3. JSON 비교 기능 개발 이슈
+ 이슈 사항 :  `<textarea />`에 직접 작성하여 비교 검사 실행 시 데이터 타입에 따라 오류 발생

+ JSON 검사 개발 코드
```javascript  
  let diff = Object.keys(o2).reduce((diff, key) => {
    if (o1[key] === o2[key]) {
      return diff;
    }
    return {
      ...o2,
      [key]: o2[key] + " (#값이 다름)",
    };
  }, {});
  ```

<br />

+ 케이스1 (결과: 정상 작동)
  + o1, o2 데이터를 JSON 형태로 받아올 경우 비교 검삭 정상 출력
```javascript
  let o1 = { name: "hello", age: 20 };
  let o2 = { name: "world", age: 20 };
  ...
  // JSON 검사 개발 코드
  ...
  console.log(diff); //출력 결과: { name: 'world (#값이 다름)', age: 20 }
```

<br />
  
+ 케이스2 (결과: 오류 발생)
  + 검사하는 데이터 타입이 Sting 이거나, JSON 형태가 아닐 경우 오류 발생
```javascript
  let o1 = `{ name: "hello", age: 20 }`;
  let o2 = `{ name: "world", age: 20 }`;
  ...
  // JSON 검사 개발 코드
  ...
  console.log(diff);
  /*출력 결과: 
   {
    '0': '{',
    '1': ' ',
    '2': 'n',
    '3': 'a',
    '4': 'm',
    '5': 'e',
    '6': ':',
    '7': ' ',
    '8': '"',
    '9': 'w',
    '10': 'o',
    '11': 'r',
    '12': 'l',
    '13': 'd (#값이 다름)',
    '14': '"',
    '15': ',',
    '16': ' ',
    '17': 'a',
    '18': 'g',
    '19': 'e',
    '20': ':',
    '21': ' ',
    '22': '2',
    '23': '0',
    '24': ' ',
    '25': '}'
  } */
```
  
### 현재 개발 현황 (임시 방안)
+ `요구사항1` 예제 코드 데이터로만 실행되도록 임시 조치 (수정 불가)
  + `요구사항3` 개발 단계에서 직접 작성하는 데이터로 코드 비교하도록 개발 예정
+ 예제 코드
  ```javascript
  // JSON1
   {"name":"hello", "age":20}
  
  // JSON2
   {"name":"world", "age":20}
  ```

+ 진행사항: #3 이슈 이관

**Comment by Kyoo130** [comment]
#3 추가 개발 완료로 이슈 이관
